R1-N1:
  rm03:
  - theta: 0.0
    x: -8.0
    y: 0.0
  - theta: 0.0
    x: 8.0
    y: 0.0
  rm04:
  - theta: 3.14
    x: 8.0
    y: 0.0
  - theta: 3.14
    x: -8.0
    y: 0.0
R1-N2:
  rm03:
  - theta: 0.35
    x: -7.0
    y: -3.0
  - theta: 0.35
    x: 7.0
    y: 3.0
  rm04:
  - theta: 1.57
    x: 7.0
    y: -3.0
  - theta: 0.0
    x: 0.0
    y: 0.0
